tap "apple/apple", "http://github.com/apple/homebrew-apple"
vscode "ms-dotnettools.csdevkit"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ritwickdey.liveserver"
vscode "visualstudiotoolsforunity.vstuc"
